apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-us-east-1a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1a
  encrypted: "false" 
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: arma3epoch
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
